author: Vanadium Authors
description: Syncbase is a storage system for developers that makes it easy to synchronize app data between devices. It works even when devices are not connected to the Internet.
homepage: https://github.com/vanadium/mojo.syncbase
name: syncbase
version: 0.0.32
dependencies:
  mojo_sdk: 0.2.17
dev_dependencies:
  dart_style: any
  test: any
environment:
  sdk: '>=1.12.0 <2.0.0'
